### ISSUE TITLE
2.2. template-project

### ISSUE THREAD

**Issue by nabeix** [tectech-dev/nabeix-study#8]

**Comment by nabeix** [comment]
把握

**Comment by tsugehara** [comment]
template-projectは、 mocha + supertestでgeoserverとかはテストを書いていて、templateはjasmineで書いているという問題があります。ご留意を。

**Comment by nabeix** [comment]
なるほど...
気になった点としては、npm startでgeomap-sever-protoはpm2使ってますね。
